export type BriefingItem = {
  title: string;
  section: "今日焦点" | "世界与新知" | "值得细读" | "人物、自然与轻读";
  format: "brief" | "standard" | "feature" | "visual" | "social";
  source: string;
  sourceType: string;
  time: string;
  href: string;
  discovery?: string;
  discoveryHref?: string;
  labels?: string[];
  recommendation?: string;
  verificationNote?: string;
  relatedSources?: Array<{ label: string; href: string }>;
  voices?: Array<{
    platform: string;
    author: string;
    text: string;
    href: string;
    engagement?: string;
  }>;
  details: string[];
  visualStat?: { label: string; value: string; note: string };
  image?: string;
  imageAlt?: string;
  imageCaption?: string;
};

export const briefingMeta = {
  dateCode: "20260828",
  headline: "从 800 米新路到一座还在蓄水的湖",
  updatedAt: "2026 年 8 月 28 日 · 20:00 晚间更新 · 公开来源综合读讯",
};

export const briefingItems: BriefingItem[] = [
  {
    title: "吉隆救援推进到 800 米：通信恢复、物资到位，但堰塞湖成为新的风险线",
    section: "今日焦点",
    format: "feature",
    source: "澎湃新闻／央视新闻／新华社",
    sourceType: "救援进展／现场见闻",
    time: "8 月 28 日 01:29—07:34",
    href: "https://www.thepaper.cn/newsDetail_forward_33964853",
    discovery: "微博热搜：#西藏吉隆泥石流#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E8%A5%BF%E8%97%8F%E5%90%89%E9%9A%86%E6%B3%A5%E7%9F%B3%E6%B5%81%23",
    labels: ["持续更新", "跨境灾害", "救援现场"],
    image: "https://imgpai.thepaper.cn/newpai/image/20260828/5b13d735-cc27-4cb7-a999-2eb2ade3fa5a.jpg",
    imageAlt: "西藏吉隆泥石流灾区的救援人员和现场道路",
    imageCaption: "救援人员向吉隆口岸方向挺进。图片来源：澎湃新闻／央视新闻",
    visualStat: { label: "截至 27 日 18 时", value: "800 米 / 499 / 555", note: "受灾路段抢通约 800 米；499 名群众完成安置；555 名滞留游客完成转移" },
    details: [
      "吉隆口岸方向的救援进入‘边抢通、边监测、边转移’阶段：通往口岸的受灾路段已抢通约 800 米，热索村恢复部分通信；青稞、大米、面粉、帐篷、饮用水等生活物资陆续运抵，受灾群众和滞留游客被分批安置、转移。",
      "公开报道仍以 27 日上午的阶段性统计为基础：成功搜救 2 人、排查发现 3 人遇难、558 人失联，其中外籍人员 260 人。救援力量已抵达，但核心区道路、天气和上游水情仍在影响可达性，数字和风险判断应按最新通报阅读。",
    ],
    verificationNote: "报道之间的时间点不同：800 米、通信恢复和物资数量来自 27 日晚至 28 日早间更新；558 人失联沿用 27 日上午排查口径。",
    relatedSources: [
      { label: "新华社：挺近吉隆口岸救援现场见闻", href: "https://www.xinhuanet.com/politics/20260828/22c26d1f181b45b1837692d64b786a9c/c.html" },
      { label: "人民日报海外版：最大限度争取救援主动", href: "https://paper.people.com.cn/rmrbhwb/pc/content/202608/28/content_30177741.html" },
    ],
  },
  {
    title: "同一场灾害的五种现场声音：有人抢通道路，有人守着水位，有人等信号",
    section: "今日焦点",
    format: "social",
    source: "澎湃新闻／新华社／水利部／Reddit 公开讨论",
    sourceType: "公开发言摘录／现场报道",
    time: "8 月 27 日—28 日",
    href: "https://www.thepaper.cn/newsDetail_forward_33964853",
    discovery: "Reddit 公开讨论：Nepal-Tibet floods",
    discoveryHref: "https://www.reddit.com/search/?q=Nepal%20Tibet%20floods",
    labels: ["多声部热点", "4 条代表性发言", "观点不合并"],
    image: "https://imgpai.thepaper.cn/newpai/image/20260828/15497de2-d749-4b66-805c-1a17f50c44f7.jpg",
    imageAlt: "救援人员在西藏吉隆泥石流灾区开展无人机和道路勘察",
    imageCaption: "救援人员沿受灾路段踏勘并回传现场影像。图片来源：澎湃新闻／央视新闻",
    details: [
      "同一热点里，救援人员关心的是下一段路能不能走，通信部门关心的是信号能不能先到，水利部门盯着的是堰塞体和雨水情，专家解释灾害链条，公开讨论则在追问数字为什么变化。它们属于不同信息层，不把它们压成一个统一结论。",
    ],
    voices: [
      {
        platform: "澎湃新闻／央视新闻",
        author: "前方救援报道",
        text: "记录受灾路段抢通约 800 米、物资运抵和群众转移，现场工作仍是沿途踏勘、排查风险、实时回传。",
        href: "https://www.thepaper.cn/newsDetail_forward_33964853",
      },
      {
        platform: "新华社",
        author: "通信管理局局长 尼玛多吉",
        text: "介绍 27 日 16 时许成功抢通 1 座基站、新增 2 座基站，距离口岸方向 3 公里的热索村恢复通信信号。",
        href: "https://www.xinhuanet.com/politics/20260828/22c26d1f181b45b1837692d64b786a9c/c.html",
      },
      {
        platform: "水利部",
        author: "洪水防御应急响应",
        text: "把重点放在堰塞体稳定性、蓄水体量和雨水情变化，提醒下游及时转移受威胁人员。",
        href: "https://www.news.cn/politics/20260827/92aa91c98e464f0d938d4343999cb815/c.html",
      },
      {
        platform: "Reddit",
        author: "公开讨论帖",
        text: "围绕失联人数、道路是否打通以及公开画面多集中在准备阶段展开追问；这些是网友意见，不等于现场事实。",
        href: "https://www.reddit.com/search/?q=Nepal%20Tibet%20floods",
      },
    ],
  },
  {
    title: "台风“沙德尔”进入红色预警：28 日早晨至中午登陆，浙闽沿海先迎最强风雨",
    section: "今日焦点",
    format: "visual",
    source: "中央气象台／中国气象局／央视网",
    sourceType: "台风红色预警／路径预报",
    time: "8 月 27 日 10:00—18:19",
    href: "https://news.cctv.cn/2026/08/27/ARTIWeMsgLmrd0zzGssGYAEu260827.shtml",
    discovery: "抖音热榜：台风沙德尔实时路径",
    discoveryHref: "https://www.douyin.com/search/%E5%8F%B0%E9%A3%8E%E6%B2%99%E5%BE%B7%E5%B0%94",
    labels: ["红色预警", "浙闽沿海", "防灾信息"],
    image: "https://www.news.cn/politics/20260827/ceeef69bcfaa49bf8c3fac1e46bb3f3f/20260827ceeef69bcfaa49bf8c3fac1e46bb3f3f_202608274b64c88939f94f29a3dab36c4c8ede57.png",
    imageAlt: "台风沙德尔影响区域的风雨预报图",
    imageCaption: "台风“沙德尔”路径与影响区域预报图。图片来源：中国气象局／新华网",
    visualStat: { label: "预计登陆强度", value: "12—14 级", note: "28 日凌晨至中午在浙江三门到福建霞浦一带沿海登陆；局地降雨 100—150 毫米" },
    details: [
      "中央气象台继续发布台风红色预警：‘沙德尔’预计 28 日凌晨至中午登陆浙闽沿海，登陆时可能达到台风级或强台风级。东海、台湾海峡北部、长江口和杭州湾以及浙江、福建北部沿海将出现强风。",
      "预报还提示浙江东部、福建东北部和台湾岛西南部有大到暴雨、局地大暴雨。路径和强度会随新一轮观测调整，沿海作业、港口设施、户外集会和山洪地质灾害防范是眼下最直接的行动项。",
    ],
  },
  {
    title: "江西省委副书记、省长叶建春被查：中央纪委国家监委发布通报",
    section: "今日焦点",
    format: "standard",
    source: "中央纪委国家监委网站／新华社／央视网",
    sourceType: "纪律审查和监察调查",
    time: "8 月 27 日 16:02",
    href: "https://www.news.cn/legal/20260827/75d541198d8f4611a91aa05e444603ef/c.html",
    discovery: "微博热搜：#江西省长叶建春被查#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E6%B1%9F%E8%A5%BF%E7%9C%81%E9%95%BF%E5%8F%B6%E5%BB%BA%E6%98%A5%E8%A2%AB%E6%9F%A5%23",
    labels: ["公共事务", "官方通报", "后续待公布"],
    details: [
      "中央纪委国家监委网站 27 日通报：江西省委副书记、省长叶建春涉嫌严重违纪违法，目前正接受中央纪委国家监委纪律审查和监察调查。通报只公布了调查启动这一节点，具体问题和后续处理以官方进一步发布为准。",
    ],
  },
  {
    title: "吉隆口岸方向堰塞湖估算蓄水 200 万立方米：雨水还可能继续把风险推高",
    section: "今日焦点",
    format: "visual",
    source: "水利部／新华社／澎湃新闻",
    sourceType: "洪水防御响应／风险监测",
    time: "8 月 27 日 13:00—28 日 07:34",
    href: "https://www.news.cn/politics/20260827/92aa91c98e464f0d938d4343999cb815/c.html",
    labels: ["堰塞湖", "次生风险", "数据卡片"],
    image: "https://imgpai.thepaper.cn/newpai/image/20260828/92ecd519-1a1a-425c-bb58-d8b5338a1cfc.jpg",
    imageAlt: "中国安能工程救援人员勘察西藏吉隆口岸方向堰塞湖",
    imageCaption: "吉隆口岸方向堰塞湖勘察画面。图片来源：中国安能／澎湃新闻",
    visualStat: { label: "水利部 27 日估算", value: "200 万 + 300 万", note: "当前蓄水量约 200 万立方米；未来 3 天预计仍有约 300 万立方米入湖，溃泄风险高" },
    details: [
      "水利部 27 日启动针对西藏的洪水防御Ⅳ级应急响应，并派专家组赶赴吉隆县。公开信息显示，堰塞湖位于尼泊尔错坚河汇入普热普强藏布的交汇处附近，蓄水体量、堰塞体稳定性和下游受影响范围都在持续监测。",
      "这条线索把救援从‘清理已经发生的淤泥’带到‘防范下一轮洪水’：当地未来几天仍有降雨、雷暴大风和冰雹可能，任何关于风险解除的判断都需要等待最新监测与会商。",
    ],
    verificationNote: "数字是水利部门在 27 日的估算，不是实时水位仪表盘；‘溃泄风险高’是公开通报中的风险判断，不代表已经发生溃泄。",
    relatedSources: [
      { label: "新华网：无人机侦查堰塞湖情况", href: "https://www.news.cn/politics/20260827/9849d49154b04a54a674d2913a754645/c.html" },
      { label: "央视新闻客户端：成因与救援进展", href: "https://news.cnr.cn/native/gd/20260827/t20260827_527795258.shtml" },
    ],
  },
  {
    title: "风暴在不同平台上长成三种语言：气象参数、地方提醒和热榜动画",
    section: "今日焦点",
    format: "social",
    source: "中央气象台／嘉兴气象台／抖音热榜",
    sourceType: "公开预警与平台热度",
    time: "8 月 27 日 07:23—18:19",
    href: "https://news.cctv.cn/2026/08/27/ARTIWeMsgLmrd0zzGssGYAEu260827.shtml",
    labels: ["多平台共振", "3 条代表性发言", "热度不等于强度"],
    details: [
      "同一场台风在不同平台被翻译成不同的观看方式：中央气象台给出风雨参数，地方气象台把它落到杭州湾水面和回港提示，热榜则把路径变化变成连续观看的公共画面。它们服务的不是同一个问题。",
    ],
    voices: [
      {
        platform: "中央气象台",
        author: "台风红色预警",
        text: "给出 12—14 级登陆强度、100—150 毫米局地大暴雨，并提醒防范强降水引发的山洪和地质灾害。",
        href: "https://www.news.cn/politics/20260827/ceeef69bcfaa49bf8c3fac1e46bb3f3f/c.html",
      },
      {
        platform: "嘉兴气象台",
        author: "地方台风预警",
        text: "把影响落到杭州湾水面和沿海风力：27 日中午至夜间逐渐增强，28 日早晨至中午可能达到最强，并伴有雷阵雨。",
        href: "https://www.nmc.cn/publish/alarm/33040041600000_20260827100718.html",
      },
      {
        platform: "抖音热榜",
        author: "台风沙德尔实时路径",
        text: "以路径动画和实时画面形成观看热点，公开榜单曾显示热度值 1172.9 万；榜单热度不是气象强度指标。",
        href: "https://www.douyin.com/search/%E5%8F%B0%E9%A3%8E%E6%B2%99%E5%BE%B7%E5%B0%94",
        engagement: "聚合榜单热度 1172.9 万（页面可见记录）",
      },
    ],
  },
  {
    title: "工业利润前七月增长 17.6%，集成电路行业同比增长 18.5 倍",
    section: "世界与新知",
    format: "visual",
    source: "国家统计局／财新",
    sourceType: "工业利润数据／经济报道",
    time: "8 月 27 日 09:30—15:21",
    href: "https://www.stats.gov.cn/sj/zxfbhjd/202608/t20260827_1965126.html",
    discovery: "百度热搜：集成电路行业利润同比增长 18.5 倍",
    discoveryHref: "https://www.baidu.com/s?wd=%E9%9B%86%E6%88%90%E7%94%B5%E8%B7%AF%E8%A1%8C%E4%B8%9A%E5%88%A9%E6%B6%A6%E5%90%8C%E6%AF%94%E5%A2%9E%E9%95%BF18.5%E5%80%8D",
    labels: ["商业经济", "AI 产业链", "结构分化"],
    image: "https://img.caixin.com/2026-08-27/178781550476333_840_560.jpg",
    imageAlt: "河南焦作工业企业生产制造现场",
    imageCaption: "工业企业生产制造现场资料图。图片来源：视觉中国／财新",
    visualStat: { label: "2026 年 1—7 月", value: "17.6% / 18.5 倍", note: "规上工业利润同比增长 17.6%；集成电路行业利润同比增长 18.5 倍" },
    details: [
      "国家统计局公布，1—7 月全国规模以上工业企业实现利润总额 45820.6 亿元，同比增长 17.6%；营业收入同比增长 6.5%，营业收入利润率为 5.66%。财新梳理认为，上游原材料和中游装备制造较快，而下游消费品制造偏弱。",
      "AI 和算力需求把电子行业推到聚光灯下：计算机、通信和其他电子设备制造业利润同比增长 1.1 倍，集成电路行业利润同比增长 18.5 倍。但这组数字同时提醒，产业链的景气并不是所有行业同步变好，汽车、农副食品和部分传统制造仍有压力。",
    ],
    relatedSources: [
      { label: "财新：AI 相关行业成为利润支撑", href: "https://economy.caixin.com/2026-08-27/102478569.html" },
      { label: "新浪财经：集成电路行业数据拆解", href: "https://finance.sina.com.cn/roll/2026-08-27/doc-inipttav9048310.shtml" },
    ],
  },
  {
    title: "一张利润表的三种读法：算力在加速，传统制造却没有一起起飞",
    section: "世界与新知",
    format: "social",
    source: "国家统计局／财新／公开财经讨论",
    sourceType: "数据发布与市场讨论",
    time: "8 月 27 日",
    href: "https://economy.caixin.com/2026-08-27/102478569.html",
    labels: ["多声部热点", "3 条代表性观点", "不替数据下结论"],
    image: "https://img.caixin.com/2026-08-27/178781550476333_840_560.jpg",
    imageAlt: "工业企业生产线上的设备和工人",
    imageCaption: "工业生产线资料图。图片来源：视觉中国／财新",
    details: [
      "同一份工业利润数据，统计部门强调增长与结构变化，媒体把它写成 AI 相关行业对全局的拉动，公开讨论则继续追问这是不是‘算力繁荣、需求分化’。保留这些不同读法，数据本身不替任何一方完成判断。",
    ],
    voices: [
      {
        platform: "国家统计局",
        author: "工业司首席统计师 于卫宁",
        text: "解释人工智能加快拓展、算力需求扩张和相关产品价格上涨，带动电子行业利润高速增长。",
        href: "https://www.stats.gov.cn/sj/zxfbhjd/202608/t20260827_1965126.html",
      },
      {
        platform: "财新",
        author: "记者 程思炜",
        text: "把电子行业对全部工业利润增长贡献过半，与下游消费品制造业偏弱并置呈现，强调增长的结构性。",
        href: "https://economy.caixin.com/2026-08-27/102478569.html",
      },
      {
        platform: "公开财经讨论",
        author: "市场参与者",
        text: "围绕‘AI 产业链是否能外溢到更广泛需求’展开讨论；这是市场观点，不是统计口径。",
        href: "https://finance.sina.com.cn/roll/2026-08-27/doc-inipttav9048310.shtml",
      },
    ],
  },
  {
    title: "霍尔木兹海峡又有油轮遇袭：卡塔尔、巴基斯坦继续寻找伊朗战争的降温出口",
    section: "世界与新知",
    format: "feature",
    source: "美联社／英国海事贸易行动办公室",
    sourceType: "国际局势／能源通道",
    time: "8 月 27 日",
    href: "https://apnews.com/article/middle-east-iran-israel-west-bank-august-27-2026-c457cd178b05f6c39c8c2e33f0a565ba",
    discovery: "X 公开信息：Strait of Hormuz",
    discoveryHref: "https://x.com/search?q=Strait%20of%20Hormuz&src=typed_query",
    labels: ["国际", "能源通道", "外交斡旋"],
    image: "https://dims.apnews.com/dims4/default/d00e509/2147483647/strip/true/crop/6000x4000%2B0%2B0/resize/599x399%21/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2F12%2F19%2F6e7f4a3d8031e59f3cba04308370%2F0378bbaa80ee4f52bc13940a2971ce8b",
    imageAlt: "伊朗霍尔木兹海峡附近停泊的商船",
    imageCaption: "霍尔木兹海峡附近停泊的商船。图片来源：Amir Biazar／ISNA via AP",
    recommendation: "原文看点在于把外交、航运和当地现场放在同一张图上：停火谈判不是抽象口号，它会直接改变一条能源水道的通行、保险和风险价格。",
    details: [
      "美联社报道，卡塔尔首相兼外交大臣访问德黑兰，讨论降低冲突升级的努力，以及由伊朗和阿曼提出的安全通行、清除海峡水雷方案；巴基斯坦也在继续与伊朗接触。与此同时，英国海事贸易行动办公室收到油轮被不明弹体击中并起火的报告，船员安全，暂未报告环境损害。",
      "霍尔木兹海峡的船流仍低于战争前水平，但上周油气运输船数量较前一周增加约 50%。这意味着外交窗口和航运压力同时存在，新闻中‘有船通过’不等于风险已经消失。",
    ],
  },
  {
    title: "AI 服务器不只消耗芯片，也开始消耗城市的水、电和耐心",
    section: "值得细读",
    format: "feature",
    source: "The Guardian Science Weekly",
    sourceType: "科技环境播客／公共讨论",
    time: "8 月 27 日 15:55 CEST",
    href: "https://www.theguardian.com/science/video/2026/aug/27/everyone-hates-datacentres-do-we-really-need-them-video",
    labels: ["高质量文章", "AI 基础设施", "城市环境"],
    image: "https://i.guim.co.uk/img/media/5894d269bcde533863ad1af84f7c2c4e89927c17/0_0_1280_720/1280.jpg?crop=none&dpr=1&s=none&width=1200",
    imageAlt: "关于人工智能数据中心扩张的报道配图",
    imageCaption: "AI 数据中心扩张引发的公共讨论。图片来源：The Guardian",
    recommendation: "原文看点是把‘AI 很重要’往下追问一层：数据中心到底由谁供电、谁承担用水和噪音、地方社区有没有真正的否决或协商空间。",
    details: [
      "The Guardian 的 Science Weekly 讨论英国及全球数据中心扩张引发的反弹：AI 公司承诺改变世界，但服务器园区同时带来噪音、用水、用电和土地压力。争议不只是技术要不要发展，而是基础设施成本如何被看见、分配和谈判。",
      "在英伟达财报和 AI 基建投资升温的同一天，这条内容提供了另一种尺度：芯片营收是季度数字，数据中心却会在一个社区里留下多年甚至数十年的电网、景观和资源账单。",
    ],
    relatedSources: [
      { label: "The Guardian：英国数据中心专题", href: "https://www.theguardian.com/uk-news/datacentres" },
      { label: "The Guardian：AI 数据中心公共争议", href: "https://www.theguardian.com/science/series/science" },
    ],
  },
  {
    title: "苹果把秋季发布会定在北京时间 9 月 10 日凌晨：一张蓝色邀请函留下许多问号",
    section: "世界与新知",
    format: "visual",
    source: "Apple／Apple Developer／The Verge",
    sourceType: "官方发布／产品前瞻",
    time: "8 月 26 日—27 日",
    href: "https://developer.apple.com/news/?id=s6spdug0",
    discovery: "微博热搜：#苹果发布会定档#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E8%8B%B9%E6%9E%9C%E5%8F%91%E5%B8%83%E4%BC%9A%E5%AE%9A%E6%A1%A3%23",
    labels: ["科技消费", "官方已确认", "传闻分开看"],
    image: "https://devimages-cdn.apple.com/wwdc-services/articles/images/EA4CFEB6-BA9E-490A-9723-5962EA23BF53/2048.jpeg",
    imageAlt: "苹果亮新篇来耀眼发布会邀请图中的发光苹果标志",
    imageCaption: "Apple Event“Surprise and shine”官方视觉。图片来源：Apple",
    visualStat: { label: "北京时间", value: "9 月 10 日 01:00", note: "发布会于美国太平洋时间 9 月 9 日 10:00 举行，官方称将在 Apple 官网、Apple TV 和 YouTube 直播" },
    details: [
      "苹果官方确认将于 9 月 9 日太平洋时间上午 10 点举行特别活动，主题为‘Surprise and shine’，北京时间为 9 月 10 日凌晨 1 点。官方目前确认的是时间、地点和直播渠道，至于具体产品仍需等发布会。",
      "邀请函的蓝色和光晕已经在社交平台引发对新配色、可变光圈和折叠屏 iPhone 的大量猜测。把这些看作发布前的用户与媒体解读更稳妥，不能把传闻写成苹果已公布的规格。",
    ],
    verificationNote: "官方页面没有确认折叠屏 iPhone、iPhone 18 Pro 或可变光圈；这些属于媒体和用户根据邀请函及供应链传闻做出的前瞻。",
    relatedSources: [
      { label: "The Verge：发布会前瞻", href: "https://www.theverge.com/tech/983407/apple-iphone-launch-event-2026-date" },
      { label: "新浪：苹果秋季发布会定档", href: "https://finance.sina.com.cn/roll/2026-08-27/doc-inipsrra0639432.shtml" },
    ],
  },
  {
    title: "英伟达 Q2 营收 962 亿美元：AI 需求被写进财报，也被写进了估值压力",
    section: "世界与新知",
    format: "standard",
    source: "NVIDIA／美联社／Axios",
    sourceType: "公司财报／市场反应",
    time: "8 月 26 日—27 日",
    href: "https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Announces-Financial-Results-for-Second-Quarter-Fiscal-2027/default.aspx",
    discovery: "Reddit：r/nvidia 财报讨论",
    discoveryHref: "https://www.reddit.com/r/nvidia/comments/1vzgn7p/nvidia_fiscal_q2_2027_financial_result/",
    labels: ["公司财报", "AI 基建", "市场讨论"],
    details: [
      "英伟达公布截至 7 月 26 日的 2027 财年第二财季财报：营收 962 亿美元，同比增长 106%，环比增长 18%；数据中心收入 890 亿美元，同比增长 117%；净利润约 597 亿美元。公司给出的下一财季营收预期为 1080 亿美元上下 2%。",
      "黄仁勋把‘AI 已到转折点、计算即收入’写进管理层叙事，投资人则继续盯着供应链、客户自研芯片、客户集中度和公司对 AI 实验室的投资。财报说明需求很强，不自动回答这轮支出能否长期转化为所有客户的回报。",
    ],
    relatedSources: [
      { label: "美联社：强劲 AI 芯片需求推动业绩", href: "https://apnews.com/article/dc8d556e709b50915cca9217a60b1991" },
      { label: "Reddit：r/stocks 财报讨论", href: "https://www.reddit.com/r/stocks/comments/1vz8np8/nvidia_announces_financial_results_for_second/" },
    ],
  },
  {
    title: "机器人在百米赛道上刷新纪录，却在锤钉子和铺床时暴露短板",
    section: "值得细读",
    format: "feature",
    source: "Nature／新华社／美联社视频",
    sourceType: "科技赛事／工程观察",
    time: "8 月 27 日",
    href: "https://www.nature.com/articles/d41586-026-02713-z",
    discovery: "微博／知乎：世界人形机器人运动会",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E4%B8%96%E7%95%8C%E4%BA%BA%E5%BD%A2%E6%9C%BA%E5%99%A8%E4%BA%BA%E8%BF%90%E5%8A%A8%E4%BC%9A%23",
    labels: ["高质量文章", "机器人", "从比赛到场景"],
    image: "https://www3.xinhuanet.com/tech/20260827/136847e5df86442c9cb895910179c15a/20260827136847e5df86442c9cb895910179c15a_416fb26bac9d4f0da616776da5ac8f20.JPG",
    imageAlt: "人形机器人参加北京世界人形机器人运动会百米比赛",
    imageCaption: "人形机器人参加百米决赛。图片来源：新华社",
    recommendation: "原文看点在于把‘跑得比人快’放回工程问题：固定轨迹的爆发动作容易优化，折衣服、铺床、锤钉子这类手眼协同才更接近日常使用。",
    details: [
      "Nature 观察第二届世界人形机器人运动会：机器人在短跑、跳跃等预设轨迹动作上刷新纪录，但在锤钉子、整理床铺、图书上架等场景任务中仍显笨拙。大型组百米冠军成绩为 8.64 秒，几乎比人类纪录快一秒。",
      "斯坦福大学计算机科学家 Karen Liu 的解释很有穿透力：对机器人而言，后空翻可能比折衣服更容易，因为前者每一毫秒都能沿着预定轨迹执行，后者需要持续处理柔软物体、接触力和不确定环境。赛事真正的价值，是把短时性能和可用性放在同一张试卷上。",
    ],
    relatedSources: [
      { label: "新华社：人形机器人赛事现场", href: "https://www3.xinhuanet.com/tech/20260827/136847e5df86442c9cb895910179c15a/c.html" },
      { label: "Nature：机器人赛事报道", href: "https://www.nature.com/articles/d41586-026-02713-z" },
    ],
  },
  {
    title: "同一场机器人赛，观众看到速度，工程师看到制动，场景团队看到一张更长的清单",
    section: "值得细读",
    format: "social",
    source: "Nature／北京日报／新华社／Reddit 公开讨论",
    sourceType: "赛事观点／观众反应",
    time: "8 月 26 日—27 日",
    href: "https://www.nature.com/articles/d41586-026-02713-z",
    labels: ["多声部热点", "4 条代表性观点", "观点仅代表发布者"],
    image: "https://www3.xinhuanet.com/tech/20260827/136847e5df86442c9cb895910179c15a/20260827136847e5df86442c9cb895910179c15a_7bb663840e0e43cb8190ef682c68f72e.jpg",
    imageAlt: "人形机器人在赛场上奔跑的现场画面",
    imageCaption: "人形机器人赛事现场。图片来源：新华社",
    details: [
      "机器人运动会的讨论同时包含速度崇拜、可靠性担忧、场景落地和观众玩笑。它们不在同一评价维度，却共同回答了‘这场比赛为什么值得看’。",
    ],
    voices: [
      {
        platform: "Nature",
        author: "计算机科学家 Karen Liu",
        text: "指出对机器人来说，折衣服等日常任务比后空翻更难，因为它们涉及高灵巧度、接触力和不确定物体。",
        href: "https://www.nature.com/articles/d41586-026-02713-z",
      },
      {
        platform: "Nature／北京日报",
        author: "赛事与工程团队",
        text: "把赛事从短跑、跳跃扩展到图书上架、铺床等场景任务，强调自主完成比遥操作更能说明系统成熟度。",
        href: "https://www.nature.com/articles/d41586-026-02713-z",
      },
      {
        platform: "新华社",
        author: "工程师 高大伟",
        text: "解释极致性能需要在速度、稳定和制动之间做折中，赛后‘撞墙’不是单一笑点，而是控制问题的现场表现。",
        href: "https://www3.xinhuanet.com/tech/20260827/136847e5df86442c9cb895910179c15a/c.html",
      },
      {
        platform: "Reddit",
        author: "公开赛事讨论帖",
        text: "网友用‘什么时候阅兵上机器人方阵’等玩笑回应比赛画面；这是观众反应，不是对技术能力的判断。",
        href: "https://www.reddit.com/r/China_irl/search/?q=%E4%BA%BA%E5%BD%A2%E6%9C%BA%E5%99%A8%E4%BA%BA%E8%BF%90%E5%8A%A8%E4%BC%9A",
      },
    ],
  },
  {
    title: "会收缩的肌肉移植物让老年小鼠获得部分运动收益，但还远不是‘不用运动’",
    section: "值得细读",
    format: "feature",
    source: "Nature／Nature Aging",
    sourceType: "科研论文／同行评议解读",
    time: "8 月 26 日",
    href: "https://www.nature.com/articles/d41586-026-02664-5",
    labels: ["科研进展", "动物实验", "谨慎阅读"],
    image: "https://media.springernature.com/w290h158/magazine-assets/d41586-026-02664-5/d41586-026-02664-5_53167680.jpg",
    imageAlt: "Nature 报道中的收缩肌肉移植物科研配图",
    imageCaption: "收缩肌肉移植物研究示意配图。图片来源：Nature／Springer Nature",
    recommendation: "原文看点是把吸睛标题拉回实验边界：目前只是小鼠研究，人体安全性、侵入性、移植数量和长期效果都没有答案。",
    details: [
      "Nature 报道一项研究：研究者把小鼠肌肉干细胞培养成能持续收缩、并与血管连接的肌肉组织，再移植到皮下。接受移植的老年小鼠在瘦体重、骨密度、握力和跑步表现等指标上优于对照组。",
      "这不是注射替代运动的临床方案。外部专家指出，若要获得小鼠实验中涉及全身的收益，可能需要多处移植；对虚弱、高龄或卧床人群而言，多次侵入性操作本身就有风险。研究的价值在于提示肌肉作为‘活体组织器官’的可能性，而不是给出生活方式捷径。",
    ],
    relatedSources: [
      { label: "Nature Aging：论文解读", href: "https://www.nature.com/articles/s43587-026-01191-2" },
      { label: "论文 DOI：Contractile myografts", href: "https://doi.org/10.1038/s43587-026-01190-3" },
    ],
  },
  {
    title: "带状疱疹疫苗与心血管风险下降有关联，但关联不是处方",
    section: "世界与新知",
    format: "visual",
    source: "Nature Medicine／Nature",
    sourceType: "医学研究报道",
    time: "8 月 26 日",
    href: "https://www.nature.com/articles/d41586-026-02663-6",
    labels: ["健康研究", "大样本观察", "不替代医疗建议"],
    image: "https://media.springernature.com/w290h158/magazine-assets/d41586-026-02663-6/d41586-026-02663-6_53170258.jpg",
    imageAlt: "Nature 关于带状疱疹疫苗与心脏健康研究的配图",
    imageCaption: "带状疱疹疫苗研究配图。图片来源：Nature／Springer Nature",
    visualStat: { label: "研究对象", value: "> 70,000 人", note: "研究比较接受当前重组疫苗或较早配方疫苗的人群，并观察心脏病与心衰风险差异" },
    details: [
      "Nature 报道一项发表在 Nature Medicine 的研究：在超过 7 万名接种当前重组带状疱疹疫苗或较早配方疫苗的人群中，接种与较低的心脏病和心衰风险相关。报道说的是统计关联，不等于已经证明疫苗直接预防心血管疾病。",
      "这类结果的阅读重点是研究设计、比较组和潜在混杂因素，而不是把一条观察性研究改写成新的接种建议。个人是否接种、何时接种仍应根据当地指南和医生建议决定。",
    ],
  },
  {
    title: "伦敦 Kew 的老温室要修五十年：有些树必须离开，有些树却因此得到回到野外的机会",
    section: "人物、自然与轻读",
    format: "feature",
    source: "The Guardian／Kew Gardens",
    sourceType: "自然保护／人物现场",
    time: "8 月 27 日",
    href: "https://www.theguardian.com/science/2026/aug/27/kew-gardens-london-palm-house-renovation-project",
    labels: ["自然", "长期阅读价值", "保护与取舍"],
    image: "https://i.guim.co.uk/img/media/cb1d77fc06d6244bc743160fc23f1e23022dcb78/1073_0_5978_4782/master/5978.jpg?crop=none&dpr=1&s=none&width=1200",
    imageAlt: "伦敦邱园棕榈屋内的热带植物",
    imageCaption: "Kew Gardens 棕榈屋内景。图片来源：Sarah Lee／The Guardian",
    recommendation: "原文看点是把一次温室维修写成一堂保护课：搬迁、扦插、种子、野外回植和不得不砍掉的高大树木，都在同一项工程里发生。",
    details: [
      "伦敦邱园的维多利亚时期棕榈屋有约 1000 株植物，16,000 块玻璃和铁结构正在老化，团队开始把植物搬入后台苗圃，为计划中的翻修做准备。高大棕榈树无法整体移动，部分必须砍伐；另一些濒危植物则通过扦插和种子获得延续。",
      "一个有余味的转折是 Ravenea moorei：温室里的雄株原本被担心是仅存个体，研究人员后来在科摩罗找到野生种群，并已培育出 10 株幼苗。Kew 不是单纯保存一间漂亮温室，而是在尝试把收藏重新送回野外。",
    ],
    relatedSources: [
      { label: "Kew：棕榈屋翻修背景", href: "https://www.theguardian.com/science/2025/jul/16/kew-gardens-tropical-palm-house-close-net-zero-makeover" },
      { label: "The Guardian：植物与再野化专题", href: "https://www.theguardian.com/science/kew-gardens" },
    ],
  },
  {
    title: "今晚美洲可见接近全食的月食：地球的影子会把月面染成暗红色",
    section: "人物、自然与轻读",
    format: "visual",
    source: "The Guardian／天文学公开预报",
    sourceType: "天文现象／观测提示",
    time: "8 月 27 日晚间（当地时间）",
    href: "https://www.theguardian.com/science/space/2026/aug/27/all",
    labels: ["天文", "自然观察", "区域可见"],
    image: "https://i.guim.co.uk/img/media/db707aa5218ff69df77081a1e336a158df9680e7/280_0_3488_2792/master/3488.jpg?auto=format&fit=max&quality=85&s=837e387cf019f0c6b3961fbaf2b81722&width=1200",
    imageAlt: "月食期间呈暗红色的月亮",
    imageCaption: "月食观测资料图。图片来源：The Guardian",
    visualStat: { label: "主要可见区域", value: "北美 × 南美", note: "月面进入地球本影时，散射后的阳光会让月亮呈现红色；具体观测时间以当地天文预报为准" },
    details: [
      "The Guardian 的天文预报提醒，北美和南美部分地区 27 日夜间可以看到接近全食的月食。月食不需要特殊设备，找一处视野开阔、远离强光的地方即可观察；双筒望远镜能增加细节，但不是必需品。",
      "它适合成为一条慢消息：与台风的路径、财报的数字和救援的倒计时不同，月食只要求人抬头看一会儿。",
    ],
  },
  {
    title: "狗狗会对着同伴眨眼：一条轻巧的研究，提醒我们注意很小的社交信号",
    section: "人物、自然与轻读",
    format: "social",
    source: "Royal Society Open Science／ScienceDaily／公开科研解读",
    sourceType: "动物行为研究／轻阅读",
    time: "8 月 27 日",
    href: "https://www.sciencedaily.com/news/plants_animals/nature/",
    discovery: "Phys.org 今日科学图读：dogs may use blinking as a subtle social signal",
    discoveryHref: "https://phys.org/visualstories/2026-08-27-daily-top.amp",
    labels: ["轻阅读", "动物行为", "可靠收尾"],
    image: "https://www.greenreport.it/media/yootheme/cache/7b/i%20cani%20possono%20usare%20il%20battito%20delle%20ciglia-7b48d1d5.jpg?hash=d8648747&src=images%2Fnews%2Fi+cani+possono+usare+il+battito+delle+ciglia.jpg&thumbnail=1104%2C727%2C",
    imageAlt: "展示狗狗不同面部表情和眨眼动作的研究配图",
    imageCaption: "狗狗眨眼行为研究配图。图片来源：GreenReport／Royal Society Open Science",
    details: [
      "一项发表在 Royal Society Open Science 的研究观察狗狗观看同伴视频时的反应：当视频里的狗眨眼，观看者也更常眨眼。研究者把它看作可能的模仿或沟通信号，而不是简单的人类式‘卖萌’。",
      "它没有宏大结论，却给日常相处留了一个小提示：动物的交流未必都靠叫声和动作，有时只是一个人类差点错过的眨眼。",
    ],
    voices: [
      {
        platform: "Royal Society Open Science",
        author: "动物行为研究团队",
        text: "通过让 54 只家犬观看不同面部线索的视频，观察它们的眨眼和生理反应，把眨眼作为潜在社交信号进行讨论。",
        href: "https://royalsocietypublishing.org/journal/rsos",
      },
      {
        platform: "ScienceDaily／Phys.org",
        author: "科研报道",
        text: "把研究翻译成一个容易理解的问题：狗狗会不会因为看到同伴眨眼，也用眨眼回应？",
        href: "https://phys.org/visualstories/2026-08-27-daily-top.amp",
      },
    ],
  },
];
