export type BriefingItem = {
  title: string;
  section: "今日焦点" | "世界与新知" | "值得细读" | "人物、自然与轻读";
  format: "brief" | "standard" | "feature" | "visual" | "social";
  source: string;
  sourceType: string;
  time: string;
  href: string;
  discovery?: string;
  discoveryHref?: string;
  labels?: string[];
  recommendation?: string;
  verificationNote?: string;
  relatedSources?: Array<{ label: string; href: string }>;
  voices?: Array<{
    platform: string;
    author: string;
    text: string;
    href: string;
    engagement?: string;
  }>;
  details: string[];
  visualStat?: { label: string; value: string; note: string };
  image?: string;
  imageAlt?: string;
  imageCaption?: string;
};

export const briefingMeta = {
  dateCode: "20260825",
  headline: "从“约三百人”到“解除一百零七人”",
  updatedAt: "2026 年 8 月 25 日 · 23:15 晚间更新 · 公开来源综合读讯",
};

export const briefingItems: BriefingItem[] = [
  {
    title: "星宇校招劝退争议从热搜走到通报：传播中的“约三百人”被校正为解除 107 人",
    section: "今日焦点",
    format: "feature",
    source: "常州市人社局／第一财经／澎湃新闻／公开社交讨论",
    sourceType: "晚间通报／多平台热点",
    time: "8 月 23 日—25 日 21:27",
    href: "https://www.yicai.com/news/103333595.html",
    discovery: "微博热搜：#硕士被安排打螺丝300人被迫离职#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E7%A1%95%E5%A3%AB%E8%A2%AB%E5%AE%89%E6%8E%92%E6%89%93%E8%9E%BA%E4%B8%9D300%E4%BA%BA%E8%A2%AB%E8%BF%AB%E7%A6%BB%E8%81%8C%23",
    labels: ["多声部热点", "连续专题 1/2", "微博／虎扑／新闻门户"],
    image: "https://x0.ifengimg.com/ucms/2025_45/08BB7EC88037B47357E59C479F2A487AE331052B_size1417_w1080_h607.png",
    imageAlt: "常州星宇股份厂区与办公楼全景",
    imageCaption: "星宇股份厂区资料图。图片来源：凤凰网江苏",
    visualStat: { label: "常州人社局晚间通报", value: "440 / 107", note: "招录 440 名高校毕业生，与其中 107 人解除劳动合同" },
    details: [
      "热搜最初由多名应届生的讲述和约谈录音推动：他们称以研发、技术、管培岗位入职后，被要求在“个人原因离职”和转去一线操作岗之间选择；社交平台随后把群人数变化概括成“近 300 人离职”，并衍生出套取补贴等质疑。",
      "25 日晚，常州市人社局通报称，星宇股份共招录 440 名 2026 届高校毕业生，与其中 107 人解除劳动合同；企业承认沟通“简单生硬”、表示歉意并停职人力资源总监。通报同时称未发现违规享受就业和人才类政府补贴，107 人中已有 22 人就业、14 人参加其他企业面试。",
    ],
    verificationNote: "“近 300 人”来自早期受访者按群人数变化作出的估算；晚间官方调查公布的解除劳动合同人数为 107 人。两组数字保留各自来源与时间语境。",
    relatedSources: [
      { label: "澎湃：劳动监察全面核查", href: "https://www.thepaper.cn/newsDetail_forward_33846195" },
      { label: "财中社：应届生讲述与财务背景", href: "https://finance.eastmoney.com/a/202608253852467634.html" },
      { label: "虎扑同题讨论", href: "https://bbs.hupu.com/642062423.html" },
    ],
  },
  {
    title: "同一场校招风波，七种声音谈契约、基层锻炼与就业处境",
    section: "今日焦点",
    format: "social",
    source: "微博／虎扑／受访者／常州市人社局",
    sourceType: "公开发言与晚间回应",
    time: "8 月 23 日—25 日",
    href: "https://www.sina.cn/news/detail/5335175819952391.html",
    labels: ["多声部热点", "连续专题 2/2", "7 条代表性发言"],
    details: [
      "这些声音没有被压成一个结论：当事人讲岗位落差和身体感受，媒体追问用工程序，普通用户争论“基层锻炼”的边界，地方通报则给出新的调查数字并回应补贴质疑。",
    ],
    voices: [
      {
        platform: "受访者／九派新闻",
        author: "应届毕业生“小张”",
        text: "称签约的是管理岗位，进车间后熟练时一天要打五六千个螺丝，大拇指疼了半个月；他最担心的是社保记录、背调和重新求职的时间窗口。",
        href: "https://www.sina.cn/news/detail/5335175819952391.html",
      },
      {
        platform: "微博",
        author: "闪电新闻",
        text: "把争议归纳为“签的是管理层岗位，干的却是流水线”，并发布受访学生与约谈录音中的主要说法。",
        href: "https://www.sina.cn/news/detail/5335215056881789.html",
        engagement: "671 转发 · 1,156 评论",
      },
      {
        platform: "微博",
        author: "观察者网",
        text: "转述九派新闻调查，把当事人感受、约谈条件、公司现金状况和二次赴港上市背景放在同一条长帖中。",
        href: "https://www.sina.cn/news/detail/5335175819952391.html",
        engagement: "403 转发 · 490 评论",
      },
      {
        platform: "微博",
        author: "爱在北方啊",
        text: "把问题从工资损失扩展到企业信誉：短期降本若消耗年轻人的信任，损失的可能正是上市公司的长期“护城河”。",
        href: "https://www.sina.cn/news/detail/5335175819952391.html",
        engagement: "43 转发 · 150 评论",
      },
      {
        platform: "虎扑",
        author: "lihaoming9129",
        text: "提出反向意见：企业技术和管理岗位不足、经营普遍收缩，在这种背景下能提供一线岗位也比完全没有工作好。",
        href: "https://bbs.hupu.com/642062423.html",
        engagement: "同题帖 8.8 万浏览 · 43 亮",
      },
      {
        platform: "虎扑",
        author: "青年文明好",
        text: "反驳说，一线实习本身不是问题，关键在于招聘时承诺的是研发、技术或管理岗位，岗位变化应在入职前说明，而不是入职后改写。",
        href: "https://bbs.hupu.com/642062423.html",
      },
      {
        platform: "政府通报",
        author: "常州市人力资源和社会保障局",
        text: "称企业招录 440 人、解除 107 人，沟通方法简单生硬；经查不存在违规享受就业和人才类政府补贴，后续将继续为未就业人员提供服务。",
        href: "https://www.yicai.com/news/103333595.html",
      },
    ],
  },
  {
    title: "“紫檀”停止回旋逼近华南，“沙德尔”随后将影响浙闽沿海",
    section: "今日焦点",
    format: "visual",
    source: "中国天气网／中央气象台",
    sourceType: "气象机构晚间更新",
    time: "8 月 25 日 18:09",
    href: "https://e.weather.com.cn/news/2026/08/4772532.shtml",
    discovery: "微博热搜：#台风紫檀#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E5%8F%B0%E9%A3%8E%E7%B4%AB%E6%AA%80%23",
    labels: ["微博高热", "晚间预报", "防灾信息"],
    image: "https://i.weather.com.cn/images/mobile/mtqxw/2026/08/25/F4B54EEF9F5175D6758D6F5F3CB96F76.jpg",
    imageAlt: "卫星云图显示台风紫檀结构不对称",
    imageCaption: "台风“紫檀”卫星云图。图片来源：国家卫星气象中心／中国天气网",
    visualStat: { label: "广西上思局地累计雨量", value: "超 700 毫米", note: "统计期为 8 月 21 日至 25 日 8 时" },
    details: [
      "中国天气网称，“紫檀”结束在北部湾的回旋，预计 25 日夜间至 26 日早晨在广东徐闻至广西合浦一带沿海登陆；广西前期已有 18 个水文站超警，仍需防范叠加降雨与滞后性地质灾害。",
      "强度更强、环流更大的“沙德尔”预计 27 日夜间至 28 日上午在浙江中部至福建中部沿海登陆，27 日起台湾、浙江、福建等地将先后出现强降雨。路径仍有摆动空间，以后续预报为准。",
    ],
  },
  {
    title: "记者暗访餐饮消杀：多家门店残留液体检出敌敌畏，当地已介入",
    section: "值得细读",
    format: "feature",
    source: "新京报／厦门属地监管部门",
    sourceType: "调查报道／监管跟进",
    time: "8 月 24 日",
    href: "https://www.bjnews.com.cn/detail/1787462876129890.html",
    discovery: "微博热搜：#多家餐厅残留液体敌敌畏检测阳性#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E5%A4%9A%E5%AE%B6%E9%A4%90%E5%8E%85%E6%AE%8B%E7%95%99%E6%B6%B2%E4%BD%93%E6%95%8C%E6%95%8C%E7%95%8F%E6%A3%80%E6%B5%8B%E9%98%B3%E6%80%A7%23",
    labels: ["微博高热", "值得一读", "调查报道"],
    recommendation: "报道把记者暗访、现场采样、企业回应和监管跟进放在一起，适合直接阅读完整调查过程。",
    image: "https://media.bjnews.com.cn/image/2026/08/24/5755950284832580337.png",
    imageAlt: "记者调查餐饮门店消杀作业的报道配图",
    imageCaption: "餐饮门店消杀调查报道配图。图片来源：新京报",
    details: [
      "新京报调查称，厦门一家消杀公司长期为多家连锁餐饮门店提供服务，员工把敌敌畏原液装入矿泉水瓶以规避检查。记者在多家餐厅消杀后的地面残留液体中检出敌敌畏阳性。",
      "厦门市湖里区已成立联合调查组，涉事门店陆续停业清洁。报道同时记录了企业回应和属地调查进展。",
    ],
  },
  {
    title: "天工机器人百米跑进 8.86 秒，赛场兴奋与“如何停下”同时成为话题",
    section: "今日焦点",
    format: "visual",
    source: "央视新闻／天工机器人／AP／TechRadar",
    sourceType: "晚间赛况／多平台现场",
    time: "8 月 22 日—25 日 20:17",
    href: "https://xinwen.bjd.com.cn/content/s6a8d87bce4b0e45f3fd67cc5.html",
    discovery: "微博／百度／知乎：#中国机器人连刷人类世界纪录#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E4%B8%AD%E5%9B%BD%E6%9C%BA%E5%99%A8%E4%BA%BA%E8%BF%9E%E5%88%B7%E4%BA%BA%E7%B1%BB%E4%B8%96%E7%95%8C%E7%BA%AA%E5%BD%95%23",
    labels: ["多声部热点", "微博／知乎／国际媒体", "晚间刷新"],
    relatedSources: [
      { label: "AP：竞速、跳高与现场观众", href: "https://apnews.com/article/86cb8e310843151a77057e4cb764b4e2" },
      { label: "新京报：研发团队解释性能提升", href: "https://xinwen.bjd.com.cn/content/s6a8bd3e7e4b03fa51a834eaf.html" },
      { label: "TechRadar：最大的难题是安全停下", href: "https://www.techradar.com/ai-platforms-assistants/robots-have-smashed-human-world-records-for-the-100m-sprint-and-high-jump-but-the-biggest-hurdle-is-stopping-safely" },
    ],
    image: "https://dims.apnews.com/dims4/default/aaceb24/2147483647/strip/true/crop/7752x5165+0+9/resize/980x653!/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2F38%2F87%2F73a90e94017e52915aec79c63d34%2F57d603c5440e4b1e9f69651d426846e9",
    imageAlt: "北京世界人形机器人运动会现场的人形机器人",
    imageCaption: "北京世界人形机器人运动会现场。图片来源：AP",
    visualStat: { label: "8 月 25 日百米复赛", value: "8.86 秒", note: "继开幕式 9.39 秒后再次刷新赛会纪录" },
    details: [
      "25 日晚，央视新闻报道，天工机器人在大型组 100 米复赛跑出 8.86 秒；此前的 9.39 秒百米、38.15 秒 400 米和 2.8843 米原地跳高已经让“机器超过人类纪录”成为跨平台热点。需要注意，这些是针对机器人赛制与动作方式的成绩，不能直接等同于人类田径竞赛。",
      "同一赛场既有速度和爆发力，也有冲线后摔倒、工作人员接应与可靠性讨论。热度因此分成两条线：一条惊叹一年间从 21.50 秒到 8.86 秒的进步；另一条追问高动态演示何时能转化成长时间、复杂环境里的稳定工作。",
    ],
    voices: [
      {
        platform: "央视新闻",
        author: "赛事晚间快讯",
        text: "记录天工机器人在 100 米复赛跑出 8.86 秒，并明确这是继开幕式 9.39 秒后再次刷新纪录。",
        href: "https://xinwen.bjd.com.cn/content/s6a8d87bce4b0e45f3fd67cc5.html",
      },
      {
        platform: "微博",
        author: "天工机器人",
        text: "研发团队连续发布百米、400 米和原地跳高的赛场片段，把“更高、更快、更能干”作为技术展示主线。",
        href: "https://www.sina.cn/media/7920364352",
        engagement: "公开页面显示单条互动量较低，未据此推算整体热度",
      },
      {
        platform: "AP／现场观众",
        author: "李艳凤",
        text: "她曾担心人工智能取代人类，但认为发展已经不可阻挡，因此决定亲自到现场看看。",
        href: "https://apnews.com/article/86cb8e310843151a77057e4cb764b4e2",
      },
      {
        platform: "AP／现场观众",
        author: "杨尚正",
        text: "跑步和跳跃对人很普通，如今机器人也能完成，这种反差让他觉得惊奇。",
        href: "https://apnews.com/article/86cb8e310843151a77057e4cb764b4e2",
      },
      {
        platform: "TechRadar",
        author: "Darren Allan",
        text: "把注意力从破纪录转向冲线后的控制：机器人跑得越来越快，但安全、稳定地停下来仍是最直观的工程难题。",
        href: "https://www.techradar.com/ai-platforms-assistants/robots-have-smashed-human-world-records-for-the-100m-sprint-and-high-jump-but-the-biggest-hurdle-is-stopping-safely",
      },
    ],
  },
  {
    title: "已故人士金融账户查询服务将推广，银行和保险资产可望“一站式”办理",
    section: "今日焦点",
    format: "brief",
    source: "司法部／金融监管总局／民政部",
    sourceType: "三部门联合通知",
    time: "8 月 21 日",
    href: "https://www.moj.gov.cn/pub/sfbgw/zwxxgk/fdzdgknr/fdzdgknrtzwj/202608/t20260821_538768.html",
    discovery: "百度热搜：#全国推广去世亲人存款查询#",
    discoveryHref: "https://www.baidu.com/s?wd=%E5%85%A8%E5%9B%BD%E6%8E%A8%E5%B9%BF%E5%8E%BB%E4%B8%96%E4%BA%B2%E4%BA%BA%E5%AD%98%E6%AC%BE%E6%9F%A5%E8%AF%A2",
    labels: ["百度高热", "官方原文", "公共服务"],
    details: [
      "三部门发文推广浙江、青岛试点经验，通过“个人身后一件事”联办平台一站式查询已故人士的银行、保险等金融资产信息；复制推广仍需依法核验亲属关系，并保障数据获取、传输和存储安全。",
    ],
  },
  {
    title: "时隔 14 个月，郑钦文重新在大满贯赛场赢球",
    section: "今日焦点",
    format: "visual",
    source: "湖北日报／新华社",
    sourceType: "赛事报道／赛后回应",
    time: "8 月 25 日 09:15",
    href: "https://news.hubeidaily.net/pc/c_5898864.html",
    discovery: "微博热搜：#郑钦文时隔14个月大满贯赢球#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E9%83%91%E9%92%A6%E6%96%87%E6%97%B6%E9%9A%9414%E4%B8%AA%E6%9C%88%E5%A4%A7%E6%BB%A1%E8%B4%AF%E8%B5%A2%E7%90%83%23",
    labels: ["微博高热", "体育", "赛场图片"],
    image: "https://hbrbapp.hubeidaily.net/e0b0d2a8323947848d314ad579856b4f.jpg",
    imageAlt: "郑钦文在 2026 年美网资格赛首轮比赛中击球",
    imageCaption: "郑钦文在美网资格赛首轮比赛中。图片来源：湖北日报",
    visualStat: { label: "美网资格赛首轮", value: "6–3 / 6–2", note: "直落两盘击败尤晓迪，比赛用时 1 小时 28 分" },
    details: [
      "因右肘手术长期休赛、世界排名下滑后，郑钦文从美网资格赛重新起步。她在首轮以 6 比 3、6 比 2 击败尤晓迪，终结单打三连败，也拿到 14 个月来的首场大满贯胜利。",
      "她赛后说近期状态不理想，需要靠一场场比赛找回手感；下一轮对手是法国球员克拉拉·比雷尔。",
    ],
  },
  {
    title: "余承东官宣华为第二代三折叠，发布会定档 9 月 7 日",
    section: "今日焦点",
    format: "visual",
    source: "余承东微博／上海证券报",
    sourceType: "公司高管原始发布／行业报道",
    time: "8 月 25 日 16:15",
    href: "https://weibo.com/2/detail/5335736249225240",
    discovery: "微博热搜：#余承东官宣全新三折叠#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E4%BD%99%E6%89%BF%E4%B8%9C%E5%AE%98%E5%AE%A3%E5%85%A8%E6%96%B0%E4%B8%89%E6%8A%98%E5%8F%A0%23",
    labels: ["微博高热", "产品预告", "原始发布"],
    image: "https://cdn.beebom.com/content/2026/04/mate-xts-fi_jpg.jpg",
    imageAlt: "紫色华为三折叠手机展开后的背部与铰链",
    imageCaption: "华为三折叠手机资料图。图片来源：Beebom Gadgets",
    visualStat: { label: "发布会", value: "9 月 7 日 14:30", note: "Mate XT 2 将与 HarmonyOS 7 及全场景新品同场发布" },
    details: [
      "余承东在微博宣布，HarmonyOS 7、HUAWEI Mate XT 2 及全场景新品发布会定档 9 月 7 日。Mate XT 2 将是华为第二款量产三折叠产品。",
      "官方目前只公布了产品名、时间与系统版本；具体折叠结构、芯片和影像配置仍待发布会，报道中的市场传闻不作为已确认规格。",
    ],
    relatedSources: [
      { label: "上海证券报报道", href: "https://finance.sina.com.cn/roll/2026-08-25/doc-inippmen9691870.shtml" },
    ],
  },
  {
    title: "嫦娥七号任务不满足发射条件，将不在今年预定窗口实施",
    section: "今日焦点",
    format: "standard",
    source: "新华社／人民日报",
    sourceType: "航天任务通报",
    time: "8 月 24 日",
    href: "https://cpc.people.com.cn/n1/2026/0824/c64387-40784908.html",
    discovery: "抖音热榜：嫦娥七号任务不满足发射条件",
    discoveryHref: "https://www.douyin.com/search/%E5%AB%A6%E5%A8%A5%E4%B8%83%E5%8F%B7%E4%BB%BB%E5%8A%A1%E4%B8%8D%E6%BB%A1%E8%B6%B3%E5%8F%91%E5%B0%84%E6%9D%A1%E4%BB%B6",
    labels: ["抖音高热", "官方发布"],
    details: [
      "新华社报道，有关方面经综合研判，认为嫦娥七号任务当前不满足发射条件，因此不能在 2026 年预定窗口实施。",
      "公开通报只说明了“稳妥可靠、万无一失”的原则，没有披露具体原因；社交平台随后围绕技术、供应链和合作因素出现了多种讨论。",
    ],
  },
  {
    title: "教育、社保、卫生和住房等民生支出今年安排 12.4 万亿元",
    section: "今日焦点",
    format: "visual",
    source: "财政部／国新办发布会",
    sourceType: "政策数据",
    time: "8 月 21 日",
    href: "https://www.chinanews.com/cj/2026/08-22/10682292.shtml",
    discovery: "百度热搜：#12.4万亿元关乎你的衣食住行#",
    discoveryHref: "https://www.baidu.com/s?wd=12.4%E4%B8%87%E4%BA%BF%E5%85%83%E5%85%B3%E4%B9%8E%E4%BD%A0%E7%9A%84%E8%A1%A3%E9%A3%9F%E4%BD%8F%E8%A1%8C",
    labels: ["百度高热", "政策数据"],
    image: "https://n.sinaimg.cn/spider20260306/195/w1080h715/20260306/2005-95fe00b72c514dfeb2012cf51053d2a1.png",
    imageAlt: "财政部门在新闻发布会上介绍财政政策",
    imageCaption: "财政政策新闻发布会资料图。图片来源：国新办发布会／新浪财经",
    visualStat: { label: "民生支出安排", value: "12.4 万亿元", note: "同比增长 5.4%" },
    details: [
      "财政部在国新办发布会上介绍，今年全国一般公共预算安排教育、社会保障、卫生健康和住房等方面资金 12.4 万亿元，同比增长 5.4%。",
      "发布会列出的进展还包括：预计全年超过 4,400 万人领取基本生活救助，超过 2,500 万名婴幼儿及其家庭已领取年度育儿补贴。",
    ],
  },
  {
    title: "《黑神话：钟馗》发布 15 分钟实机演示，在 B 站形成千万级观看热点",
    section: "今日焦点",
    format: "visual",
    source: "游戏科学／《黑神话：钟馗》官方发布",
    sourceType: "创作者原始内容",
    time: "8 月 20 日",
    href: "https://www.gamesci.cn/zhongkui",
    discovery: "B站热门：《黑神话：钟馗》15分钟实机演示",
    discoveryHref: "https://search.bilibili.com/all?keyword=%E9%BB%91%E7%A5%9E%E8%AF%9D%E9%92%9F%E9%A6%97%2015%E5%88%86%E9%92%9F%E5%AE%9E%E6%9C%BA%E6%BC%94%E7%A4%BA",
    labels: ["B站高热", "创作者发布", "文化科技"],
    image: "https://gamesci.cn/zhongkui/assets/img_bg_pv-CToa1Cbi.png",
    imageAlt: "《黑神话：钟馗》官方实机演示画面",
    imageCaption: "《黑神话：钟馗》官方页面展示画面。图片来源：游戏科学",
    visualStat: { label: "官方实机演示", value: "15 分钟", note: "只采用演示中可以直接看到的内容" },
    details: [
      "游戏科学公开了约 15 分钟的开发中实机画面，首次集中展示主角战斗、群体敌人和部分剧情片段。相关视频在 B 站进入热门并形成大量二次解读。",
      "官方演示发布后，社交平台围绕剧情、系统机制和发售时间展开了大量逐帧解读与观点讨论。",
    ],
  },
  {
    title: "阿里巴巴拟配售 800 亿港元新股，称净所得将全部投入全栈 AI",
    section: "今日焦点",
    format: "visual",
    source: "阿里巴巴集团",
    sourceType: "公司公告",
    time: "8 月 24 日",
    href: "https://www.alibabagroup.com/zh-HK/document-2028384807859257344",
    labels: ["公司公告"],
    visualStat: { label: "拟配售总金额", value: "800 亿港元", note: "公司称净所得将投入全栈 AI" },
    image: "https://static.alibabagroup.com/static/c33a2ec2-de56-429a-b279-2d6211a83108.png",
    imageAlt: "阿里巴巴集团公告配图",
    imageCaption: "图片来源：阿里巴巴集团",
    details: [
      "阿里巴巴公告称，拟以每股 112.70 港元配售 7.1 亿股新股，预计募集约 800 亿港元，交易完成仍取决于惯常条件。",
      "公司称净所得将用于扩建 AI 基础设施及增强从应用到算力的全栈能力；这是公司对融资用途的公开表述。",
    ],
  },
  {
    title: "热传的“蓝鲸水下哺乳”视频，被专家从眼睛、下颌和乳汁形态逐一拆解",
    section: "世界与新知",
    format: "visual",
    source: "总台环球资讯／法新社／俄勒冈州立大学研究者",
    sourceType: "跨平台视频溯源／专业解释",
    time: "8 月 22 日—25 日",
    href: "https://news.cri.cn/20260822/e866b3e6-af8a-4b7f-a19b-d6c055490453.html",
    discovery: "微博热搜：#网传蓝鲸水下哺乳视频系AI生成#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E7%BD%91%E4%BC%A0%E8%93%9D%E9%B2%B8%E6%B0%B4%E4%B8%8B%E5%93%BA%E4%B9%B3%E8%A7%86%E9%A2%91%E7%B3%BBAI%E7%94%9F%E6%88%90%23",
    labels: ["微博高热", "AI影像", "专家解释"],
    image: "https://v2.cri.cn/c89e53c6-0bc7-45ca-ac11-a385002d7d11/cb5a6d96-d0c4-4fd0-a895-b6135667d84a/image/0620339e-1f86-4e12-9453-d148a45b1407.1990x1460.750x550.png",
    imageAlt: "多平台传播的蓝鲸水下哺乳 AI 视频截图对比",
    imageCaption: "不同社交平台流传的 AI 蓝鲸哺乳视频截图。图片来源：法新社调查／总台环球资讯",
    details: [
      "这段视频被配成印尼语、英语、阿拉伯语等多个版本在海外平台传播，最早线索指向一个自称 AI 创作者的账号，画面仍带有生成平台水印；该账号此前发布的部分海洋动物视频达到数百万次观看。",
      "俄勒冈州立大学海洋哺乳动物研究所副教授凯瑟琳·亨特指出，视频里的鲸眼位置、下颌形状、幼鲸含乳方式和乳汁在水中的表现都不符合真实解剖与行为。",
    ],
  },
  {
    title: "美加贸易谈判破裂，两个长期盟友开始面对一场全面贸易战",
    section: "值得细读",
    format: "feature",
    source: "美联社 AP",
    sourceType: "国际媒体",
    time: "8 月 22 日",
    href: "https://apnews.com/article/4d18583fe52134ca8550652ad9772d2c",
    labels: ["值得一读", "国际分析"],
    image: "https://dims.apnews.com/dims4/default/0f4b972/2147483647/strip/true/crop/2929x1952+35+0/resize/980x653!/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2Ff7%2F32%2F0028f864e780861f28bdda886a8f%2F1a66736f059d4ba59339af0b1220be3b",
    imageAlt: "加拿大民众在渥太华国会山集会，回应美国对加拿大主权的威胁",
    imageCaption: "加拿大民众在渥太华国会山集会。资料图片：Justin Tang／The Canadian Press／AP",
    recommendation: "文章不仅报告关税数字，还解释谈判破裂、反制范围与盟友关系变化，适合作为理解事件背景的入口。",
    details: [
      "美联社报道，美加最后阶段的贸易谈判失败后，美国对约 200 亿美元加拿大商品加征 50% 关税。",
      "加拿大总理卡尼表示将从 9 月 8 日起采取对等反制，涉及钢铁、乳制品、家电、农业设备、纸浆和电子产品等领域。报道把这次分歧描述为两国关系的一次结构性断裂。",
    ],
  },
  {
    title: "一枚火箭上面级撞上月球，NASA 拍到了新月坑的明暗辐射纹",
    section: "世界与新知",
    format: "visual",
    source: "NASA Science",
    sourceType: "科研机构发布",
    time: "8 月 18 日",
    href: "https://science.nasa.gov/solar-system/moon/nasas-lro-images-falcon-9-crater-on-moon-learns-new-details/",
    labels: ["科研机构", "图像解释"],
    image: "https://assets.science.nasa.gov/content/dam/science/missions/lro/NASA_LRO_Falcon9impact_2026_GIF.gif?w=1200&h=1200&fit=clip&crop=faces%2Cfocalpoint",
    imageAlt: "月球表面撞击前后对比，可见新形成的月坑和辐射纹",
    imageCaption: "月球勘测轨道飞行器拍摄的撞击前后对比。图片来源：NASA／LRO",
    details: [
      "8 月 5 日，一枚完成任务后的 Falcon 9 上面级撞击月球。NASA 的月球勘测轨道飞行器随后从不同光照角度拍下新形成的月坑。",
      "照片显示出向外延伸的明暗纹路：较暗部分来自长期受太阳风和微陨石影响的表层物质，较亮部分则是撞击从更深处翻出的新鲜物质。",
    ],
  },
  {
    title: "一种仍像普通气球的材料，目标是在九个月内完全降解",
    section: "世界与新知",
    format: "standard",
    source: "Euronews／AFP／Imperial College London",
    sourceType: "科研与创业报道",
    time: "8 月 25 日 07:11",
    href: "https://www.euronews.com/2026/08/25/balloons-take-years-to-decompose-uk-researchers-invent-bioloon-as-nature-friendly-alternat",
    labels: ["科研进展", "材料", "环境"],
    image: "https://images.euronews.com/articles/stories/09/88/66/20/808x539_cmsv2_aea777d4-a030-5afc-92c6-f7d086ac01e7-9886620.jpg",
    imageAlt: "粉色和紫色的 Bioloon 可降解气球",
    imageCaption: "Bioloon 原型气球。图片来源：Bioloon／Euronews",
    visualStat: { label: "研究团队估算", value: "约 9 个月", note: "在土壤、海水和去离子水中均进行了降解测试" },
    details: [
      "Imperial College London 博士生 Juliana Cumming 与活动策划创业者 Charlotte Melia 用天然乳胶和另一种可降解聚合物做出 Bioloon，避免加入传统硫化工艺中的部分添加剂。",
      "团队称材料在三种环境中都能分解，并希望 2028 年商业化；这一时间表与降解表现目前仍主要来自开发团队公开说明。",
    ],
  },
  {
    title: "不到 10 纳米的镁薄膜，让氮化镓器件的电接触阻力进一步降低",
    section: "世界与新知",
    format: "visual",
    source: "名古屋大学未来材料与系统研究所",
    sourceType: "大学研究发布",
    time: "8 月 18 日",
    href: "https://www.imass.nagoya-u.ac.jp/research/20260818_pgan.html",
    labels: ["科研进展"],
    image: "https://www.imass.nagoya-u.ac.jp/wp/wp-content/uploads/2026/08/20260818_imass.png",
    imageAlt: "薄型 p-GaN 低电阻接触技术示意图",
    imageCaption: "研究方法与器件表现示意。图片来源：名古屋大学",
    details: [
      "名古屋大学、康奈尔大学和 MIT 等机构的联合团队提出一种薄型 p-GaN 接触工艺：沉积不足 10 纳米的镁层，再进行短时间低损伤热处理。",
      "研究团队报告的比接触电阻为 1—3×10⁻⁴ Ω·cm²，同时维持薄膜表面平整和器件耐压表现。潜在应用包括 LED、micro-LED 和 GaN 功率器件。",
    ],
  },
  {
    title: "即将百岁的她，要回到 1939 年与家人分离的维也纳车站",
    section: "值得细读",
    format: "feature",
    source: "The Guardian",
    sourceType: "国际媒体／人物报道",
    time: "8 月 24 日",
    href: "https://www.theguardian.com/world/2026/aug/24/ill-probably-feel-emotional-kindertransport-centenarian-prepares-to-revisit-site-of-family-separation",
    labels: ["值得一读", "人物长文"],
    image: "https://i.guim.co.uk/img/media/7ac2a9d5d2d90b50bd1211d5b722f538a7302d88/1042_421_6429_5143/master/6429.jpg?crop=none&dpr=1&s=none&width=1200",
    imageAlt: "Gabriele Keenaghan 在家中抱着童年留下的玩具熊",
    imageCaption: "Gabriele Keenaghan 与她在 1939 年离开维也纳时获准带走的玩具熊。图片：Christopher Thomond／The Guardian",
    recommendation: "用一位幸存者重返车站的具体行动连接家庭记忆、战争历史与教育实践，细节充分，叙事价值高于单纯纪念性消息。",
    details: [
      "1939 年，12 岁的 Gabriele Keenaghan 通过“儿童运输”计划从纳粹统治下的奥地利前往英国。她在维也纳西站与祖母道别，此后再也没有见到父亲。",
      "临近百岁，她计划和几代家人一起重返那座车站。她后来成为校长，并长期向学生讲述自己的经历，希望孩子们理解善意、宽容与多样性的价值。",
    ],
  },
  {
    title: "诺福克郡五百年来首次迎来野生河狸幼崽",
    section: "人物、自然与轻读",
    format: "standard",
    source: "The Guardian／Pensthorpe Nature Reserve",
    sourceType: "国际媒体／自然保护",
    time: "8 月 24 日",
    href: "https://www.theguardian.com/world/2026/aug/24/wild-beaver-kit-pair-born-norfolk",
    labels: ["轻阅读", "自然保护"],
    image: "https://i.guim.co.uk/img/media/5d73f1e581431d61b87c983d27938dcf0a1070f5/229_0_1515_1212/master/1515.jpg?crop=none&dpr=1&s=none&width=1200",
    imageAlt: "红外相机拍到河道中的两只野生河狸幼崽",
    imageCaption: "红外相机拍到两只河狸幼崽。图片来源：Pensthorpe Nature Reserve／The Guardian",
    details: [
      "英国 Pensthorpe 自然保护区的红外相机拍到两只约三个月大的河狸幼崽。它们的父母在去年 12 月神秘出现在温瑟姆河，此前当地已有约五百年没有自由生活的河狸记录。",
      "幼崽已经开始学习潜水和用尾巴拍击水面。保护区接下来需要解决种群基因多样性和合法引入更多河狸的问题。",
    ],
  },
  {
    title: "完整监控曝光后，六种声音仍在追问：无责救助者为何支付 1.9 万元",
    section: "今日焦点",
    format: "social",
    source: "央广网／澎湃新闻／微博公开发言",
    sourceType: "多平台热点／公开观点摘录",
    time: "8 月 23 日—25 日 11:26",
    href: "https://news.cnr.cn/dj/20260825/t20260825_527790792.shtml",
    discovery: "微博／百度／知乎：#帮扶老人遭索赔店主不担责#",
    discoveryHref: "https://s.weibo.com/weibo?q=%23%E5%B8%AE%E6%89%B6%E8%80%81%E4%BA%BA%E9%81%AD%E7%B4%A2%E8%B5%94%E5%BA%97%E4%B8%BB%E4%B8%8D%E6%8B%85%E8%B4%A3%23",
    labels: ["多声部热点", "完整监控公开", "6 条代表性发言"],
    image: "https://mediabluk.cnr.cn/img/cnr/CNRCDP/2026/0825/57ccb8f3a03a4cf7adf31a860033c08610.png?auth=b447f67fe40d7632a8b193ee8cc38e4c",
    imageAlt: "湖南祁东涉事牌馆的完整监控视频封面",
    imageCaption: "涉事牌馆完整监控视频封面。图片来源：央广网",
    verificationNote: "有关部门确认店主无过错、不承担法律责任；1.9 万元在调解协议中被表述为人道主义补偿。网络流传的“政府返还”说法没有统一公开说明，本条不采用。",
    details: [
      "央广网综合公开监控与调解协议报道：老人进店休息后很快晕倒，店主一家参与救助；有关部门确认店主没有过错、不承担法律责任，但调解协议仍记录其向家属支付 1.9 万元人道主义补偿。争论没有因“无责”认定结束，反而从事件真相转向调解边界与善意保护。",
    ],
    relatedSources: [
      { label: "澎湃：完整监控与店主家属回应", href: "https://www.thepaper.cn/newsDetail_forward_33842937" },
      { label: "央视网评论与微博讨论", href: "https://www.sina.cn/news/detail/5335557186257772.html" },
      { label: "早期索赔争议帖与互动数据", href: "https://www.sina.cn/news/detail/5335402895377708.html" },
    ],
    voices: [
      {
        platform: "当事人／央广网",
        author: "女店主一家",
        text: "在官方确认无过错后表示，感受到很多慰问和鼓励；以后再遇到需要帮助的人，仍会站出来尽力帮一把。",
        href: "https://news.cnr.cn/dj/20260825/t20260825_527790792.shtml",
      },
      {
        platform: "当事人家属／澎湃新闻",
        author: "店主儿子",
        text: "删除此前发布的视频，并写道“也许昨天需要一个答案，但是今天已经不需要了，这件事到此为止吧”，表达的是一家人想结束争议的疲惫。",
        href: "https://www.thepaper.cn/newsDetail_forward_33842937",
      },
      {
        platform: "微博",
        author: "央视网",
        text: "评论强调“有责依法担责，无责理直气壮”，认为鼓励助人为乐时，法律边界不应被“人道主义”模糊。",
        href: "https://www.sina.cn/news/detail/5335557186257772.html",
        engagement: "850 转发 · 2,461 评论",
      },
      {
        platform: "微博",
        author: "张三同学（法律博主）",
        text: "把问题压缩成一个法律判断：既然店主无责，就不应通过含混调解让善意承担额外成本。",
        href: "https://www.sina.cn/news/detail/5335557186257772.html",
      },
      {
        platform: "微博",
        author: "野生11",
        text: "情绪化地追问家属索赔和调解在此事中分别扮演了什么角色；这类愤怒表达构成了事件最主要的公众共鸣。",
        href: "https://www.sina.cn/news/detail/5335402895377708.html",
        engagement: "33 转发 · 204 评论",
      },
      {
        platform: "微博",
        author: "胡锡进",
        text: "认为即使可以通过补贴或捐助补回 1.9 万元，事情也不应以是非不清的方式了结，关键仍是把责任说清。",
        href: "https://widget.weibo.com/list/list.php?appkey=&color=&dpc=1&footbar=1&height=1200&info=1&isborder=0&language=zh_cn&listid=355322867&listname=%E6%B6%89%E5%86%9C%E5%AA%92%E4%BD%93%E4%BA%BA&showcreate=1&sidebar=1&uid=2245266941&uname=%E6%96%B0%E6%B5%AA%E5%86%9C%E4%B8%9A&width=280",
        engagement: "114 转发 · 552 评论",
      },
    ],
  },
  {
    title: "有人只用字母、数字和符号，做出了一座可以步行探索的 3D 城市",
    section: "人物、自然与轻读",
    format: "visual",
    source: "Grow Now Games／TechSpot",
    sourceType: "创作者作品／科技媒体",
    time: "8 月 21 日",
    href: "https://www.techspot.com/news/113574-fully-walkable-3d-city-built-entirely-out-ascii.html",
    labels: ["创作者作品"],
    image: "https://i.ytimg.com/vi/3YtygAx_C6A/maxresdefault.jpg",
    imageAlt: "由 ASCII 字符构成的可步行三维城市",
    imageCaption: "独立开发者展示的 ASCII 三维城市。画面来源：Grow Now Games／YouTube",
    details: [
      "一位独立开发者用 JavaScript 和 Canvas 搭建了一座赛博朋克风格城市，建筑、道路、树木、车辆和行人全部由 ASCII 字符表现。",
      "项目借助透视、景深和碰撞算法把二维字符组织成可行走的空间。它仍在开发中，但已经成为一个“用限制换风格”的有趣例子。",
    ],
  },
  {
    title: "一只从肺炎中康复的小猫，凭 29 个脚趾刷新世界纪录",
    section: "人物、自然与轻读",
    format: "visual",
    source: "Guinness World Records／The Guardian",
    sourceType: "纪录机构／动物轻读",
    time: "8 月 25 日 12:00",
    href: "https://www.theguardian.com/world/2026/aug/25/wisconsin-kitten-29-toes-world-record",
    labels: ["轻阅读", "动物", "可靠收尾"],
    image: "https://i.guim.co.uk/img/media/b489b20441af8af3380152b8635363a0aab80253/0_0_1500_1200/master/1500.jpg?crop=none&dpr=1&s=none&width=1200",
    imageAlt: "拥有 29 个脚趾的缅因猫 Erebus Anomaly",
    imageCaption: "Erebus Anomaly 拥有 29 个脚趾。图片来源：Blue Northern Maine Coons／The Guardian",
    visualStat: { label: "猫的脚趾世界纪录", value: "29 个", note: "比保持 24 年的纪录多 1 个" },
    details: [
      "威斯康星州缅因猫 Erebus Anomaly 的四只爪分别有 8、7、7、7 个脚趾。多趾来自遗传特征；它的父亲也有 24 个脚趾。",
      "它幼年曾因吸入性肺炎住进氧舱，康复后的 X 光片后来反而成为吉尼斯认证脚趾数量的重要材料。主人说，它会继续留在家里。",
    ],
  },
];
